#!/bin/bash

sudo apt-get install python-dev
sudo apt-get install python-pip
sudo apt-get install python-xlib
sudo apt-get install libxtst-dev

sudo pip install pyuserinput
sudo pip install gevent-websocket

# Might be nicer to server this up with flask...
sudo apt-get install apache2
sudo cp -r * /var/www/

echo -e "\n\nNow run the server with: \"./server.py\""
